### PR TITLE
Guard against error when the "do not challenge me" checkbox is not found

### PR DESCRIPTION
**Pull request by alexlapwood**
The "do not challenge me" checkbox doesn't always exist.

### CODE REVIEW

**Comment by alexlapwood** [comment]
Is there something I could do differently to get this change merged in? I can't use your extension without it.

**Comment by michaelabon** [comment]
@Alapwood Apologies! This PR auto-closed when I changed the default branch from `master` to `main`.

This looks like a great change. I'll merge it and build a new version of the extension. You should get it auto-updated in your browser in the next day or two.

**Comment by michaelabon** [comment]
@Alapwood Actually, can you change the base branch of this PR from `master` to `main` so that I can merge it? I want you to have credit for it.

**Comment by alexlapwood** [comment]
I couldn't update this PR so I've opened a new one (#5)

**Pull request closed without merging**
